apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  labels:
    app: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: denshiimageregistry.azurecr.io/react-app-image:${TAG}
          envFrom:
            - configMapRef:
                name: my-app-config
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
