apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp
  labels:
    app: reactapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reactapp
  template:
    metadata:
      labels:
        app: reactapp
    spec:
      containers:
        - name: reactapp
          image: denshiimageregistry.azurecr.io/react-app-image:180
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: reactapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
